[[CUDA_Runtime]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "17a0230b3726b7ec4af4041398bc7c4341494a3c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "24da452949a6fad382e37ce681fb0b5b4811079e6dc7d049f8d2f5ae0d650b51"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "10.2"
git-tree-sha1 = "1a7e1f67bfe1088c6bd37d019b2d0aeef6345a40"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "b7c55e70272268813b43603dab65d4fb9a720c8c15f8cb58f447574d5aadabe6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.powerpc64le-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "10.2"
git-tree-sha1 = "34c69574f52efe4a102eeb0e11d5bc0b58410d1d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "ca081ba6e9bec73a3d4530c4ac83406e3c54ee249b3c51d1c40431e35f2b0ee0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.aarch64-linux-gnu-cuda+10.2.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "9650d7b8c9db02a505144eda81f7e70d559dcd42"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "990ac9266b6db8d5dcc368cc096eb7e0d48c1f610567a892ee5dd88797720f37"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "e2e59684d28c6a7b73f2037c0140e5b9008ab9e6"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "bb2afb1d1cd929fd1a8f61470b74b7bfc85058db748314a587047a00e02ef4fc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "ac8aec1b1b423687b709282ffd84ba7cd1d3f81e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "40831435424997598b30d2743bea1c84bccfd4a2b2ae5a51110670bf30445936"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "fb037205b72a472142e371d016db6113186fd136"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "08fba54f05873dfbb06fb20ea87e8cff61d72405312ea231a5b8db491b0480a7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.aarch64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "3c1b075f562f0184dc9c0ac4463afcefb2240107"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "c17a107611cc9f02941e0f1a04d0c40d18d8e6d780b05b02b21ed387cffaba6e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-w64-mingw32-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "cad8445e3e171c2afc03199d6855bf83d5678096"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "d998cbcf54e41a4b334977492cee7200688a2cacdd572f7385403822be08d39a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.5"
git-tree-sha1 = "98a272e5667c3871fb83ca6f9abefb2118cfe437"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "ff0d9423cfb13cc416937e5dc81a3ceb81ed3cda80c9eb0f179e81ed0e7d2fff"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.powerpc64le-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.5"
git-tree-sha1 = "63a9456acb6807d939427ffe43b746a3e4becda5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "558ee058413bbe3f7d2b14b9b2a8cae9a084708888bd2fd67f6ecaa6a42272bd"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.aarch64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "1b0c5d848d405103f4d72ccece4f1836e204050d"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "7649a1a447cb859522676c7d242a686c84ed452f53c929eb44a3044c0ecc8d73"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-w64-mingw32-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "6af0127ce6b267d23b06bc2a70fde3a7bdcb78a6"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "ff01bbcb513dff7ea2a38592c9a879a70fae2374aa755d6ebacb776756853304"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.6"
git-tree-sha1 = "f560dbf949c1b3842372f91ce32c16fd3ac4cd87"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "4b2d654eb8c77bccd913846d38aa0044cbfd48376a7148776207200c4cc1e863"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.powerpc64le-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.6"
git-tree-sha1 = "ef12efcc65524a8e6c12b65b5ccdd2d639fd8ee5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "b023110ab296667d488f6515c9f20140aa08f1da97c1a4aff54d8ac9ff3e4877"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.aarch64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "633050e10841396fcd8d5465fcf2711c655bcd24"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "ef6572461224c77ba31c66139e36783ed948d42f27a045bcf19091b0590bfcd9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-w64-mingw32-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "dad411d0af9eb54986000e33c4fa7d970df9b7ff"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "0092728d99d2deb4e4b6ecb9f58e57a28b3b861c679d8a984ff04ceceef55ff3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.7"
git-tree-sha1 = "ffade223799c8fc5be1ad6b4b54893b100b7aba5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "0945eb466b1799d195e6edef5fad9e811e91d127d29a7c117a501cc671bf1d40"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.powerpc64le-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.7"
git-tree-sha1 = "fcedd1020afe2cf5a46e07866fe1f098d2fc3d7d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "0cba33d1c14900c73faad370f456e8ed2c1faa96f74a8cc5ffa3c38cdd18bd81"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.aarch64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "12ad3cab5203282d38215a181d2d5a05031e55d7"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "31ebc8ef69233c8c0242166cc32573109eecf9d93ece86c028aa89659adaa92d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-w64-mingw32-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "cbeaad4657a85551f4c6dab775e17a16c4320b62"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "0e81ee21f6914fca81c6ffbec6a1695e652ecf25e35566b7d61cea103d056241"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.8"
git-tree-sha1 = "50544a860c6b9efa50981f9a87ffb6452b769d15"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "90d0e479099102f0b313bd463fcf661597b63f3d4aef86021ea7727e5cf45a90"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.powerpc64le-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.8"
git-tree-sha1 = "a0c3446d6496fcbc736d3f6e1e1edfae79f1ab45"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "557f688df4cf6e4a091e691c8946839361a548d3f68d0abc179c28182c61fea1"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.aarch64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "a6293f55eaafc9d2094a635848120efca68f2423"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "3c77d0bcccb077572cf08942f11e510e4d5f7eb8e65264e6d4458cc6847b464a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-w64-mingw32-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "800c8fa507539ad88f2ba0bc4c6635dcd7c60bf4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "64cb4613f46c2a044269174c8b14dadb9ca90f7745c8adce034277d11f7615f2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.0"
git-tree-sha1 = "310b345d08d71dd45d696fe2f55e6c82899b5384"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "90e51092be2c3c1e9646342952ecd25831b6d3b8adf1caac380785739624cc7d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.powerpc64le-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.0"
git-tree-sha1 = "7606bf223425e6c8f33e61f5a06b7be8e497812d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "a3413acc316aa4cf3ebbbe63ea32edb2c1a61f8d4c135388cf3d6d5e5cc048dc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.aarch64-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "a608bfe447261e98814cf0afe1915713cfa49051"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "c0d5c07cda531ec92bf4142c2b74372b81b2bf7a8ee1ef6c6f2f2ecb7945554b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "9e8d36f713aa8f6485a800ca385ad2b37756a924"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "4eadc65bc874348cd194240ee245c3a038d87a6ce6fb9c8f390683d5aa7a3c12"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.1"
git-tree-sha1 = "b0a3c8fc3d3d6d249c9c03f63c93f46b3906eb86"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "c6f8d223c1e84c87b567bd049f168b3e3dd880973e40e9e904a510dbf3bc3c26"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.powerpc64le-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.1"
git-tree-sha1 = "aa32188d31b4c609139703626416d3cd18c16022"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "cb3f2c907197501c77186481663e9097b1143d682ffcdeb30304ba284d6275df"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.aarch64-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "d7f7e5f3e41bccfbf67853e2694dda2ab9556c8c"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "5ef02aac5109637e0b7d1fdad795be4886cfd1e9feb455500d273931fa21527b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-w64-mingw32-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "4f5127d68da63dfc58524d33a3ad0417f37f437f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "ee7d85ff2a07fb754d3f81bcb936ab7ab4c6cf2b7cbc99a6e6f353ab77493eae"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.2"
git-tree-sha1 = "a252320270dd781714713184c8e3ba66a0662dac"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "f82662a3a0e3768838f2ff5a5ac99f252532cd2bebf91b85e36f1dace2bfa191"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.powerpc64le-linux-gnu-cuda+12.2.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.2"
git-tree-sha1 = "b98cff5604a0edb0e89ef470ed7d946695bd9158"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "a9dac41a8f3317f9749d49071a50405fff19ddeb292bfbb091c72b7686da9eb5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.aarch64-linux-gnu-cuda+12.2.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "47e6dffdeb70e699e85509494ed6cf3db642b285"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "ec523691745cdf4e8431f30905cb6825f05439cd3e7d9d5e7ea5a45238793563"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-w64-mingw32-cuda+12.2.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "cd7624d0ee16df77c7cb51c4181a03dc761f76f7"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "7f8df732349fabb73da2d7bf2c38704f2c399c04e88e95c6bdf67d31f767c39b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-linux-gnu-cuda+12.3.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.3"
git-tree-sha1 = "34e707451426c0138181c83d61de19ae6dcecab5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "d20cea734f822f4e37d6e9cc241cce260cc7e379cf7e62ac89c3fc7ffc28b0c8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.powerpc64le-linux-gnu-cuda+12.3.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.3"
git-tree-sha1 = "5a6d53a033709e41b4ec6ef97059d15c41df142d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "d0f30bc60512cab76ec07eeba83a9683fee347bc27121f6d7ee17e97f514dc3a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.aarch64-linux-gnu-cuda+12.3.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.3"
git-tree-sha1 = "d08be15a382d220deb60ed99f472bed60c66e5d9"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "b12de95f7d1c276cd2ccb37f0c27228ce340e09da0c6b232dab2ad44f0c5af8c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-w64-mingw32-cuda+12.3.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "acc2d1adba43763312504e74b44696859778a523"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "d38e7c1b8b9eb8d66d1845c7d47b5edaff799fe6919218085d5b19ac97bfff83"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.4"
git-tree-sha1 = "24e8fae748f1b5bfde2c3555e96b455d7866da29"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "eef371497ca2895a5943f7d8a7ac5f479b4c91e614d6ea637b4230e9a88fda4e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.powerpc64le-linux-gnu-cuda+12.4.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.4"
git-tree-sha1 = "c40bf98411b552b1371761232802c9013eb102c9"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "168d53caad67dc6c86ad558d999bf09ef45c9eac4795b024f9b0420f1dd1a7bd"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.aarch64-linux-gnu-cuda+12.4.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "63ab070c03e23f27ee81894aba9e379936e34aa7"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "df1232b0c47c45d340a37371b9b2dc8b14ebce9e4c80c5973c12c3ee047dce30"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.13.0+0/CUDA_Runtime.v0.13.0.x86_64-w64-mingw32-cuda+12.4.tar.gz"
