[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "67ea6b3f87877f05a22ad8ef945d297c85ea45e4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "1e7b58e11637cc0fd7b3172889aa93bc52de96db4635e198ac0e0d0020d01de8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "45c0aeb52c1a21b79e7156b41e4300aeb1748bf1"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "0c290a64b8ab756cf34d45721511a33b3019012d9eac64696ce44927b0be53a5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "ef1f155777d1c3fbd8cbc74dc228464223d6ca41"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "b5221908c609d93db5992c364a365e2412ca5cce687394d716b6df7b128347da"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "2dbe6442f41ffdc55bb200fc21e8cfa64775fbef"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "c092c48e91e15b34835b7e89f0ec5eed5a4a997ffbf8dad74aa42250263fe5af"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "0960e35d48b45dec196c63342051c7360a3d587c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "ece052990084bd67af7e14dcbfdb45bc5a24b5baa6c2011f2b5de1d5e55ee06b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "bd7f0e99e4dcdbc2467dcc648acaba5cf34fc3b7"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "1c76937c3631a8c0ce8ffbff54a6a2f5f1caf13e7f393e66e82cb3e78f15713a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "2a331e5eb6d0d05a384f76c994d498d397392aa6"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "33956562fe829cc6a6da8efd3df6d1885ae397ee4036065ee16304eadb577925"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "bee8c9cf7f44c2a99886cd995bbcc97799934749"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "490f1d942cf5d7fb2989241458c66cb08256ace32735bbfb1729d5ec54d03f2b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "99d2f74a471fa1260fb25418fbfca15b9e71ebb7"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "c3a1e7fac11a2bda093026c22d49233da59e95d0c56e0569e88e6eb02ddc29fe"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "8f9d05a42bb6e5c8f70faedc4de46a3271cc5498"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "03f9af097074054d107193cfd734390031b753dc5a7d0ee5f2465361747a101d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "b5717145c9e4f0b86362e493763d65d200ae3215"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "8e305348f1ce7757312c2c5d6a24071dbfd2519cbdbe9832066d38e3a44369eb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "78dc16baf4a4ada6939d41205f537c5edfdade5e"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "eb64089858206f21aaa7a3780de716fe497bd0114904476f9708a4d34d0f6ba0"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.3.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "372508153e89e882c3c92b1f23fc8e32bd9667a6"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "f0336ef477c5774eec09eea4dd8f64c3adb9c3c19c7adcd785d7beca37df21b1"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "a971bfe86a8c068fed76fc1ef08f42187a2a8a3f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "52173510ecfd9267de1262384529cfd3f4b977802d0c461f340b1011f9784b42"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "ee6b542df28e57a746e5aba41fd731c6c607c2ce"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "083d6a48f3a258cec1521bfcd4429f58fec5a5574a8d65eb523a317fca559910"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "0d4090a7a714dc25a20feb69f839f391251d5df5"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "cae123acb06a037723583fc50451e4a474b9feeb51728ca8363dde0361d16f00"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "31fbb5b16b5d22a11a7876859d4b08ec63278dbf"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "ecb76475f809aef1a732132c1e1cbebd20f873bfc90970d7534582506aa2a221"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.5"
git-tree-sha1 = "de98d2932614a150382dc4ac29ad66bd53eaa918"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "eb12dc38ecdb0b70a2084a3ce1174b95dabae29a2d416edf63304a4e379980d7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.5"
git-tree-sha1 = "de12e7e7ff2d6673c1ad9b3d3d4ae7e1c1457bd0"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "ef97b1d72234de80df147bd4cd293f352feb1194b7e29a1d9d90cdcd351e9a37"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "f5add767605966d124c5f42aec21b44cc2707973"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "e66f1c88ce33c8f5b5af37aaac64f28216d4a894ce491596a5961a12cfdea6f3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "f8ec7fd3a4257b57303061391c1a646a58f3a036"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "431e31349a65f508099255da6c00da016af7e289e644685ada7613776f2a2ccb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.6"
git-tree-sha1 = "3ad028776901fde2b7fa9bbb9ff3d8826bad625b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "3fa2c2892ca4a74af3c357d2ad530fcf625f35cea3acea37ec7d034714bc0372"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.6"
git-tree-sha1 = "f579e902ac74d55b757b7b8e91c5d56398bc8443"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "f454ad837cc85f39421b11bd98d3e71cc2ec81d69c3f1eadac615fcb20fe6209"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "d13a35eaadef4ef25d715fa7ce6bcd6073868f5f"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "3577c512f680d1342aa4e1327f7509adff53de790a601db6bc80f4c92c653d4e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "6a631bb4e756f49a0a5efb0d15bfb96795e26359"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "895cacb5a57cf319c723a1a8749543546e7305f3156ad5a30c48fbbf79358dbb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.7"
git-tree-sha1 = "b50047789179995ca60a92e05b9cd267db71c3c6"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "8f765a0e9fef19a0b06f127c9ce121f5c0c9c65026ddafb99947febf11db3276"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.7"
git-tree-sha1 = "de1b3e092d0da25dc70e1300806e107d52e4b563"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "46e9bf717e5bb102fe565d76cd9a78731c5fb033745e9321c2ed449e1b96fec6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "52ee7c0c0aa15f4d0b79085f992e79c59f0ad581"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "747916c10cd05e5827c912ebbd7d59d4bd454198acb8f8762e3108bf6716d6ad"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "abf7d982f82022fc8d16d3c62ba4bbb340e3ce1c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "634c73e8bd1ff8eae2c0b6d95a74e7ec5befe3085bd8804f3267a21efa47d596"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.8"
git-tree-sha1 = "05d9709e0145953ae5fef69138e08470e74732b5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "f59625a88a373df0aeb61c83355205861373ef1b7c121c3839667cce60e4ef1a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.8"
git-tree-sha1 = "386a928748f251552bc4c9cd4c3cba929ca27619"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "f4980e436b8eb9508267d6a62f2b369169684eadaf34388168f249b6b3e5d704"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "edde03fe02f9c01a39b7954bb72b514f09c7acec"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "666d116510719b8d929d6ad39baba472ed5b42c84bc16a5615ed926a30d52ca5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "3c855ff486ca8afa9c5bb9876d1cc5f1eadf6c50"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "f3c22be7693b9a7bd58cbfc65e2f3ece65760b395bc9c2fabf95bfb533d0f742"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.0"
git-tree-sha1 = "5cdd1979a7ec4efa7576d9961eac78f6bcdde983"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "6a2406746c9368079715f008d9132ceaef3bb3dabef271a900b7d32998372b4d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.0"
git-tree-sha1 = "eb633ed86cf3909553b7814f8bc2f5a8b103df48"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "059e0a384bfd215f613041ce5f90d91a971f4f1f6f2423998047c35110ae014b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "247259b48b28d576db845f47f1ba9cf63eea3bc2"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "d47b78949396d68582dee0e6988f45488851a461d7e5e824504b2ce99dbe892f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "e684020c4a0418cef52e8f61118edd17098b9d7b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "cf595a6dc748b85e0150a8610cfe1b4833c579d8bead4f06f7209c0501fb869f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.1"
git-tree-sha1 = "acb5314c5b2c3e604e8488ddc7d59335aade3d2d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "9acd0de3948311e0e61fd36fa7cfe2af0a677fca7b19d1b927690013d1f38d5f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.1"
git-tree-sha1 = "2e0b82db2e6e4764c3ff0cae7ca18a1c504a9422"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "1a75f79ec6ecd09f3b012b9c2106827ebc4fc51bf0e7f6e6cb26db32bd487733"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "628649b6b67b6406220f207f71c663ccfb275570"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "948d32c3ab070ccc3b4250b69def24ea33ba8a96a7673eadd1e96aeaa819c914"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+1/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+12.1.tar.gz"
