[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "b5e1c93e792c02b69a1c9755ff123cdda248851c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "91a6c0ab9b26572b6f4ad82db41920442521d16456ac7f8e382682247f35e932"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "c3e2a7be76e59bf366be139503bebf595a244e27"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "8f93b466c50d75e584dbc122f42cd36ed87bf68d1354c09a03c47fec3aeb05c9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "e9c7ae9e43cc17985dbf4203f3786d1bd3262d54"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "de73de31c51a98a1defd83456b667ecb94677dea1bc8bd1d0d725fa666207b6e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.aarch64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "2e9e75263f3f845105b6ff9bae01a215c9baca9c"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "3914d0f08de634b7864b468ca397548dd917cc6e51145a433369c7de38673064"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-w64-mingw32-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "78c441fe75c3adc8a8c5b05b1dc2924969172d39"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "6f19c0c28d8d48e322f3afe5b49af7de70feb09774ae2e0f15a8f68e6d6c66a4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.5"
git-tree-sha1 = "d6ea0ebb58038be2533dabda7b646e852ee066ee"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "b47cd731b8fee393d297dc4f4471f593fb7819855b06cfae18b12425b5ce758d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.powerpc64le-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.5"
git-tree-sha1 = "ecf332ccfe0beb98145849bd73056029ab1aba59"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "87d2f545830084d74beeba3517a7b7b755b7cba4f82372ac0d7f4bd0bfe75aca"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.aarch64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "2daadbda36bc45547dd2ad95356544ff4438f53c"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "c1bd27a62ee119a5d566d0c00ec82989ae5dc77ad544d21ec09e6da0400dcfcf"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-w64-mingw32-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "b0ca43ba7cee4b0c745f84fa81e5a7764a4106dd"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "98edc43a752300da899fe9266b53b5f1d312e92af2788b6d22cca46415b6ac98"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.6"
git-tree-sha1 = "454edccae9554eb39b783dd9c63a8da634490b2b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "b717d2be70533bf8d6a9596ed3db23c9e43596f776e102ce3ce5d241b3647782"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.powerpc64le-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.6"
git-tree-sha1 = "9173d534bad5a3e6e424d76d069b2beb034ad5d0"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "c7392631356b92a1773ee3f4ce40855e0d15c92823fe05335ac1cd9971dd0906"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.aarch64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "d54dd53bbd73d117911225b7b589391532a4c4ab"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "3f966a01c675941e081af9c9cac4edf16bd62c0279a2688046fb1f8516215e62"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-w64-mingw32-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "234468be9c4ab4cd4d3c37dadf26eb18fe4a9512"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "cd68d63af0624161a2340b666a019adcd27f8e9dd46904e3a6bf9ae761a018fe"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.7"
git-tree-sha1 = "87fbadbb4a55128f78b9c425dc71287fb7ae6717"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "9e356c0e6e6047d8a31c8a6300cab8d82bf74f561dfe4d0c9c622c29af4226fc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.powerpc64le-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.7"
git-tree-sha1 = "4616b54aafba8d0ae31077b1ef389e02cf2b5666"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "ce35e1e75de86aea17ace3f1c33ae95f400d50bc62dc7b32676e91e402b76c85"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.aarch64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "fd9b5198eab7a1b950df423be8f0174dbaeb52c5"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "14dd6bd26f4029048bee538e131cbc98d83d5fd7a62c8a7418736936a6815633"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-w64-mingw32-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "ab68cff0bd5bb9f1a8437f4b88ac4b1b8f833b2e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "78a5754bd48fea2edc3325b9972b6ac5588d4f8cfea825cf633b52b819f0e08a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.8"
git-tree-sha1 = "749e8e09a2ffcf0556db571282ac4e04bb4ddf90"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "37d193117830252a2fdd1ce2a5c4b4f6441bbf9670578c5a3f62170c1d6020e3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.powerpc64le-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.8"
git-tree-sha1 = "2d5fd3767a2ccf2ef4a8044a51ef6af3e81f0bf5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "659df76397a3574eff0865de0fc156ebcd4e48a2879491376d951c47857b6295"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.aarch64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "7880532cdfc56609933ad4bbef57ea9a4a42e0bf"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "77ef850566e66754c0318b969c27ff1da9f877f5e7760cdc2520cc24aedda628"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-w64-mingw32-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "b2ba0a64ad34f39f3dcf76d17fc3dc818e932b3e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "e621ef5297ef455e160842f6be17445e32810e166398cfbc3bf62507757443f1"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.0"
git-tree-sha1 = "af3981d6af955cce8ee3d2985a4f6681297eaa0a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "6483cb1edf5312ac4475c65812c20fef8f40bc6422488c615fdc9f9044506a95"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.powerpc64le-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.0"
git-tree-sha1 = "cfa031bf45d6c427d58379da80f7edc86a582290"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "c6799166950328ccb01a1309d689a4287b0da84b7186f703e13788867c0d1ed5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.aarch64-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "1f2aac7098df4cf1a3bf497791f6eab4b30bf279"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "d9e81ba1f67de953437cfedca8ecadd4f80d57e900fcd1c546dceb5fec36f10b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "1e95be968d79fd11d015839f08fb47a8f7d0193d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "b14d4c752f751b16627f982daa20e70fc8be5470ab2e1bc44c804e415cd56326"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.1"
git-tree-sha1 = "70bfb338f229b5f1849fb13222cd3c723c59170a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "2ffe1aea281463200f9aacfe40c9106372c1d7c606162d5757393ede503a4993"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.powerpc64le-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.1"
git-tree-sha1 = "9fc13f0476a355271ba9f827e4008caae0724ee0"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "daf1b23dfcf50dfb1bc064be80c95e8c5e6360aeed5991e120b94e036425386c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.aarch64-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "daca6ceebbf9d1157cf637f5f6979c58aed70e51"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "c6a08e62e2f06b22bddbcdc592473c9a6f713343130d4d2daddfa0f79edcb9bf"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-w64-mingw32-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "e22703892311db2869af2d2c41ecbbe8e72596c3"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "44518b2f386793a85415144d1266592548e57299a12aedc97c2e961f78c4ccda"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-linux-gnu-cuda+12.2.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.2"
git-tree-sha1 = "49bb79373389a86d99f52b807c44a06c48b47f51"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "9741ad686e57c707c821d16f741178652ea30c9383f70f106f859b40513a0eaf"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.powerpc64le-linux-gnu-cuda+12.2.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.2"
git-tree-sha1 = "e1e3881ab5ebe5cbcbba5b4471cd949053a37ef5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "03b53114df251e23e86ebcdddc962e5376c009d111f3be761ac41244dc41b703"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.aarch64-linux-gnu-cuda+12.2.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.2"
git-tree-sha1 = "0cdffaf70d865a7149744c4c5670ea6b2145e80d"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "005827451e8e5a9f7fe3a8fe8ecd659b622fb8a6e84821f97a427025aea7447c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.9.2+0/CUDA_Runtime.v0.9.2.x86_64-w64-mingw32-cuda+12.2.tar.gz"
