[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "dae1b526f6a6786a90889c65bbea36a60a396576"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "f5e83e50b9fd7ccf6b567be4b371bd5c32232f8fac8a7e385bbb3be6c59ab556"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "e96fa91fc4da7068183a339efa739cb0ebd94bff"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "cf8bbe7a1da2dce555203bed5aba9ff0d3b636d319a53a1b6f23ceb9f96e82a5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "9bdee7eb67b3a630f86651d88e2444d6b1e00674"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "7c1c51688f40b3cfc8b7a3221c2f1b2eab33c4b22a433a85f119161c114b6818"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "9ecc460282654e6e865c373ee52701b5ea600a10"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "91c898824d8b41d84815c76da3e86d655f36ccd938975ec8074b0ab0d052d323"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "c55627707f4e3aed9d9bce6e8008ee7960a8543d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "22bcbee9500b786bc8ed5af73aa0da1f0ed7f123430ef238b18ac32878911fc9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "489dbc48aa201ff536e3d37fc95157e289a64d3a"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "6b726f4becc098c9dab593dc1a642aabba93daa12917cd1793550c50bcf08062"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "52392ae95b2df6ebdb18841f96ad728e11a9ef2c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "30af44027679157b3c4b061739ff1b57dcfafed2ff94087294d284d49ad745ef"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "f0c0bf40dc97a0b9409e2a0b73fbee96146dd1da"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "620bbc8ecd14aa62c4b7c5e0b8f11e69c796fccd94b79d2855fb4d67cf68870b"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "768ac1086ce9e738c6c8ca697352f6c6466a2bbe"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "26aeebfc2010e10dc4e14493f8d3a80040dfaa59ec98405abe565c83941e33f6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "339790d14b4fbc47e6066493f013cfb3ae018a4a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "e77b284e1979df735495d5ae58f9ccec81b4070ecc223b13b6760860ffccc1b4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "0ffebfda1a8901248019362028cb87edf183daa2"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "a78e459648487cbf9f332e995167c2ef4c4b636c8ec4d35e9f8fe656b7199ce7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "41b3327aa6847a2a7f14332e70185c56d4d44515"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "7912a396dd5d8fec61b26fcf2ccf1878092ff628b6fbc6ccabc00cd719589819"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-w64-mingw32-cuda+11.3.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "4379d94d6b6c708a4985064749a87b7f1a545908"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "57b31bae0ce62f7f092ad7d9cf23e0b9f1223c022ee60b05dce96f0a06ccfebc"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "1d31987dc3b6c541f71fe697e3f5d08cef95a0ed"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "a124cb0a6a9b64e2c67d79960563bf3b5acb561a92b6ff5c808a7bb022511d2f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "048903771485268a66a97ecd3ee19be3501f4cf4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "1934b88a3670640f26da3adf925ad3424b0810cc8650a9f479b278457677c0a1"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.aarch64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "8e92efa43a33d4371ad74d0411da93afbcb55dba"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "8a795942a723b6c0d0a0ac4eca583636300d8f68b2d5e6d59c7602a2b5e9249c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-w64-mingw32-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "a5b346b9fe4ba94a96176dc91b1c80cf2d9c0219"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "1597f69fe416e2338487f63829758d9c128446b6d40cc8c02d815b39bf727b66"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.5"
git-tree-sha1 = "953ef1bde1c79f2d5f790fd79ab90628b13848b8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "2ff10eada43d7c6107dcf526c884019e279b760b4dc665952896b3797b49f913"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.powerpc64le-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.5"
git-tree-sha1 = "f2c070e861f4677e41159d9d904d45963c475fef"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "eb1c10e0cc02611fe03e9d09a496795b7e94c19ae6acd43279dd102cf06a8aba"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.aarch64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "81b3db02392edb2311f8692bc56c8a7d52b43608"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "f3af97320dd8eb2f8094cf900ea3bba6f45d122f4e0b9051f81ecee7530eef1c"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-w64-mingw32-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "e380177ef23574ed5fe4f91898cf54f29ef86f8c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "1e72212738223338734632cf42c77ca5fe4e21e39e110b592dc88c7a8e3aae53"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.6"
git-tree-sha1 = "0c75abc6d37942913b44762a835b43e45fa2a130"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "14e7aa280ed98bceebbc879f64b018ab290aae4961fec10994aa2e9b61e6c1d2"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.powerpc64le-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.6"
git-tree-sha1 = "7f6b08278232c45326c3337ad27b2a51d3de5d4b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "0b92ebefced5c4b72d84c08bea67d45f45ff5699182de54f39fbf6927b471b33"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.aarch64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "55d5ce8fbfeb757d58dfdbc1efb31e73c586ba3b"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "2513e630c83f3e8c5f35eb0f6eef1e2681fb3b3352c910c71e100efb8fdb9750"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-w64-mingw32-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "dd832292bc233bda1e353d4f2d33c0409a9195cd"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "2a489b386bfe7d2994e20c41073fa720f6926fce3b707ec5ec2c25c70a157559"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "534759902986a160c0f96bffe4d7af29a256295c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "d341bf8b598706b87b3f181772d7a604c1b02a46db45045b20c4be7280a78d5d"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.7"
git-tree-sha1 = "356b38fe2c9ad0f1dadc549618397c76c7e5d8df"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "3eb74f6281d32740da90fe99e5887b834e6abdca028351fa69fc6bad5733faf8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.powerpc64le-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.8"
git-tree-sha1 = "97eee0a5b21b182719528d9899cc742918235bb3"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "3f9ce6935c46f37672b3265c469a1f0987be5e0f22114415034da7408d106cf5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.powerpc64le-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.7"
git-tree-sha1 = "68bea03bcce34df130a6d4db2da2f29aa9442272"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "6026152c4331553b6a8aa5eb24050a259065e0132951e5f48610d05c4e301455"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.aarch64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.8"
git-tree-sha1 = "0d98e0904c7c7cec39e95d1c0d1bcd4ffc7f4307"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "e2f5d88ddfdef8e2e40c820b88fda61bb883276687e5489cb6eed8d67e3038de"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.aarch64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "88a2d91c210bf98addfb25b52c345bd51cf56453"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "dcc18bd2b704cf06318dfaa67172b18c37ffee63c2a729e88f2948e038e689a3"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-w64-mingw32-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "186748cc026fabc2316c7bb2eb636cf0714a4d85"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "dafc9c6dca35c33b28cb444f48243fc4e21bdb5cf107b9c6a89e92187ec3b812"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.2.0+0/CUDA_Runtime.v0.2.0.x86_64-w64-mingw32-cuda+11.8.tar.gz"
