[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "18c0a972d8ad535e1a59fdc4e01bb51d83aa21f6"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "20ee193c1b124faf3a9c903678ff604230d70c8c626ad64c1454f56befd61f52"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "281ece47a780e75fae948cd1111c66c91f4d7a22"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "9362efb5fee52a3759a85dec1d34db8bed4628789ba2d756092ad01152f8b4ef"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "750007912d8e9dd37f532cee49c81e381fe29b94"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "56398e6050ce6e8dd97d004fe959ab2584a16bedd7b9ea02ecb21b8023ba5132"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "084397e491cebd0c8beae9f8bcda05d4c991f45c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "3c90405d866ccd3da20312ccb67d296fff5c86047a1917852c7024615c2cd0a6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "695cfbf2f147af04540180e72df8c5b8347b9f64"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "d02ee86ae918ef984abd1f610142ec4e46228dce1fad552e664f240add72e762"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "05d8dc3612dd54b2607ab330b3c143a20d4583bb"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "2dc34246eb41cb817c0d24abac78e2fd8b759edb87a515b09a43424730d3042a"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "f959bb80bea013629496ab38c577db47bf4ddeff"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "2514b77150a9187262df99525ef289e8919a4e03537f5355d018e2b7ffd77507"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "bb63cccae0813e165ab7612e0a52998a3722fb04"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "f06e9cb8f8bc2b190c1e16fb2012f5206ae6d166063ce12209077bd2a92f35b6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "fbcc95b3a7a797554319c114dbc9d283d924dad7"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "bbf740c53e251585953d19cfcedd0342e720861429bb4a1e1b527e5083f09226"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "2580bde1e4ac33c00bb3174d5f9511a64f3e56ba"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "f4766a7a49124f3bd91b283652b0b2aca629bc2ff3b168b45231348a8dec0ed5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "9e8d8c5094bb383356c1facab8b8b7851724e648"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "36dd638470b959bf01aabf7556f12f0a760ad2381a8ddcf47341568f070b503e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "cbf8216925aec834420a8b79c1c1d4d0458d7307"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "b86c085fed9f329f6224041f1e7e4a4d046b8015b7dd09dd0fb79f90c34ad7bb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.3.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "9d4736651c241be9ae308285ca72c23e665a5442"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "ccc9544b93490f9efbe415ae90d08a485aa5f1ee7a810fe80461a733c6a424fb"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "20e59cebf55fd89de4dd827d42445d37ea5cc267"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "0a361d8153704c4945a758349833688f53c92154d18dc33d1dc8d85d5546b3f5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "dc4f61d8835a42fa74ea395621df3968286a5702"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "6e8d01b888f982432543ed0873e301172f28004eb9e418a070038d4a2009c1d9"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "5104cbf7a0164829573ced08fd4482fee02c1af4"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "9a2e73a3b4e621ba498a71b006df231a457b871c4e9663d720c18e7746f2f8fa"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.4.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "bf2f864cdebf2f3e0fb8c2fc16b0c33723f3daad"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "bdffc3136407cafa49e3b165a5b6d5b4404433c2608f50332b3f7894df71f851"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.5"
git-tree-sha1 = "bd98c4bdc4518505de279eea4d22a6be8b45bcb5"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "6a4fa58e88cbdd730c3c96dbcc3cef93a7cfdec69d99b29271f36f00fc5789d8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.5"
git-tree-sha1 = "e96b9bf1eb6e34b3a91f3584c435ae31ce6c8c34"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "d7bab59414332ff9b0183a2b6fecf221282d12d185e0e49cd5adf9630381b610"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.5"
git-tree-sha1 = "fd050b0c7f9c8426ffa8b725f3cb99b112d507f1"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "8f6f3adc6daae7dd3277829ad2845e8c51a0e0ece8c3a9fa6c2289d285a25c52"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.5.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "d777c679b567a1f145a88135a0a5f4528ad1d679"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "56d1d6ea8f6dfa82c10d7d3d046a5a618959679be5228eb4689e9b334b11f139"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.6"
git-tree-sha1 = "8595b55497450da02456a981f0a8a1029547c8f2"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "f39812ec1f6c316efc8ff91d420b780a4e64f6a306c4df2a4ee7f2f3cbb2b346"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.6"
git-tree-sha1 = "eebf6e7773658d7badebe6808aecbafc765d40be"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "8faa1e7c8e236a639bbc2700916ee7cab8190554eda169281cde40d4ab8d5e76"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.6"
git-tree-sha1 = "bc393aaac23fc2e8e607b40277b3970eac2d3f67"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "22d77043d8f28303d2c484ef4f184ed40eea52be533318b7d061dd2dc48de7a8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.6.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "185938d9250df2dab26841f74d269613b43214ab"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "4be7d9defe8a76fd84cffdb189daa873c00006728bbbbef82cff8277e4b21d51"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.7"
git-tree-sha1 = "1a73c8826dd9f550308303c19d9cb3adac5678c6"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "5ebdf88bc32c4e3dce79ae59ddfff23a506918307e29bdaa8d15b393ba971dd4"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.7"
git-tree-sha1 = "404569b17397bb62ad2c68f2124750439d7e784a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "885d031308e03f33ab35c7d19060663bf2c80d14b894f62e977ecec72148939f"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.7"
git-tree-sha1 = "37e634028b35b5f7df0d6955a02a63b5c1930c07"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "856d1d361937781f897abae29635d2b189fe78ce479b1ef574ca55d37c9263b6"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.7.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "095a955eb96de5d2b0cb5a434d0dadf145e246ca"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "67c3cb49b3c572048e827a6d2e8f1653665fb25552171e1e27476b1d07216d3e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "11.8"
git-tree-sha1 = "773c77f7b898e7fb717c4ae99ba82a6f15514039"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "a32a712071602d7f1e066b82376e760e080fdc1b8323813c7863e79f7d7142a7"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "11.8"
git-tree-sha1 = "252d654ac884dc83ee1ed26671badc9c5ef28f6a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "6ce1e26b0efc6b8cfafd95f95efa001253d9f9428ee16a31d357fdeee22b2fbe"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "11.8"
git-tree-sha1 = "b8557dd47599977d99bad87a43127c5ab7d40257"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "9630f8c0fb77ef97f9738eadbad5ad51e115a97accc5d513e1db0903d366f3dd"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+11.8.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "078c47879cb300e9bc8c8c127352afd141bdfd48"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "2a9a868b6a69971ce9eb149c52357cd6b1c8d6b2431c9856324a33fba6458865"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.0"
git-tree-sha1 = "7524bdf31ac39189ebd05f845be0a547dbbdd617"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "719b128d658f3e78f363911d71d2dd22f96280b57678247db0f4511e9c7373d8"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.0"
git-tree-sha1 = "f98d3c81b3c1d01d27636d11fb492876dbc07c55"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "5c85a70c08745263285ca89d25398bcb12ed0e974448c6d009b56a2019e00e51"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "7b8684359de1cd29fa31d38bbcbc8c85fd560310"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "07e5ec9ef173047d16413be37174ea34a9f8df48c1ce9ff4ccf790fb92e9aaf5"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "28605e58122d8c44f2ec2875aaa005cf1a3deb91"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "d13f664eb23c8daca8c6dccab8772f543da391054b0277e0755f136270c11472"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "powerpc64le"
cuda = "12.1"
git-tree-sha1 = "20a29371d231c9bc3232c9788b971986f944699b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "cf8d722c40c09cca6353eba8369a039520c21b1ebf37bf6b029058fedf1ef038"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.powerpc64le-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "aarch64"
cuda = "12.1"
git-tree-sha1 = "28bab5dad867c5cb7561eee58d252f6043c3b375"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDA_Runtime.download]]
    sha256 = "91251d874896d63f6fcebfe4a23cabe83d3463a239643d22f373e4e1daf7f48e"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.aarch64-linux-gnu-cuda+12.1.tar.gz"
[[CUDA_Runtime]]
arch = "x86_64"
cuda = "12.1"
git-tree-sha1 = "4bb47f16935256b95f0219bb6d2a8964964a31fd"
lazy = true
os = "windows"

    [[CUDA_Runtime.download]]
    sha256 = "0d751f1e396515c9b6f6bf6581e1f06e0fbb0cbd957f3108ddcaa5aa840da189"
    url = "https://github.com/JuliaBinaryWrappers/CUDA_Runtime_jll.jl/releases/download/CUDA_Runtime-v0.4.0+0/CUDA_Runtime.v0.4.0.x86_64-w64-mingw32-cuda+12.1.tar.gz"
