# Autogenerated wrapper script for CUDA_Runtime_jll for x86_64-w64-mingw32-cuda+10.2
export libcublas, libcudart, libcufft, libcupti, libcurand, libcusolver, libcusparse, libnvperf_host, libnvperf_target, libnvrtc, libnvrtc_builtins

using CUDA_Driver_jll
JLLWrappers.@generate_wrapper_header("CUDA_Runtime")
JLLWrappers.@declare_library_product(libcublas, "cublas64_10.dll")
JLLWrappers.@declare_library_product(libcudart, "cudart64_102.dll")
JLLWrappers.@declare_library_product(libcufft, "cufft64_10.dll")
JLLWrappers.@declare_library_product(libcupti, "cupti64_102.dll")
JLLWrappers.@declare_library_product(libcurand, "curand64_10.dll")
JLLWrappers.@declare_library_product(libcusolver, "cusolver64_10.dll")
JLLWrappers.@declare_library_product(libcusparse, "cusparse64_10.dll")
JLLWrappers.@declare_library_product(libnvperf_host, "nvperf_host.dll")
JLLWrappers.@declare_library_product(libnvperf_target, "nvperf_target.dll")
JLLWrappers.@declare_library_product(libnvrtc, "nvrtc64_102_0.dll")
JLLWrappers.@declare_library_product(libnvrtc_builtins, "nvrtc-builtins64_102.dll")
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Driver_jll)
    JLLWrappers.@init_library_product(
        libcublas,
        "bin\\cublas64_10.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcudart,
        "bin\\cudart64_102.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcufft,
        "bin\\cufft64_10.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcupti,
        "bin\\cupti64_102.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcurand,
        "bin\\curand64_10.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcusolver,
        "bin\\cusolver64_10.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcusparse,
        "bin\\cusparse64_10.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvperf_host,
        "bin\\nvperf_host.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvperf_target,
        "bin\\nvperf_target.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvrtc,
        "bin\\nvrtc64_102_0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvrtc_builtins,
        "bin\\nvrtc-builtins64_102.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
