# Autogenerated wrapper script for CUDA_Runtime_jll for x86_64-linux-gnu-cuda+12.1
export libcublas, libcublasLt, libcudart, libcufft, libcupti, libcurand, libcusolver, libcusolverMg, libcusparse, libnvperf_host, libnvperf_target

using CUDA_Driver_jll
using CUDA_Compiler_jll
JLLWrappers.@generate_wrapper_header("CUDA_Runtime")
JLLWrappers.@declare_library_product(libcublas, "libcublas.so.12")
JLLWrappers.@declare_library_product(libcublasLt, "libcublasLt.so.12")
JLLWrappers.@declare_library_product(libcudart, "libcudart.so.12")
JLLWrappers.@declare_library_product(libcufft, "libcufft.so.11")
JLLWrappers.@declare_library_product(libcupti, "libcupti.so.12")
JLLWrappers.@declare_library_product(libcurand, "libcurand.so.10")
JLLWrappers.@declare_library_product(libcusolver, "libcusolver.so.11")
JLLWrappers.@declare_library_product(libcusolverMg, "libcusolverMg.so.11")
JLLWrappers.@declare_library_product(libcusparse, "libcusparse.so.12")
JLLWrappers.@declare_library_product(libnvperf_host, "libnvperf_host.so")
JLLWrappers.@declare_library_product(libnvperf_target, "libnvperf_target.so")
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Driver_jll, CUDA_Compiler_jll)
    JLLWrappers.@init_library_product(
        libcublas,
        "lib/libcublas.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcublasLt,
        "lib/libcublasLt.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcudart,
        "lib/libcudart.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcufft,
        "lib/libcufft.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcupti,
        "lib/libcupti.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcurand,
        "lib/libcurand.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcusolver,
        "lib/libcusolver.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcusolverMg,
        "lib/libcusolverMg.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcusparse,
        "lib/libcusparse.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvperf_host,
        "lib/libnvperf_host.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvperf_target,
        "lib/libnvperf_target.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
    if isdefined(CUDA_Compiler_jll, :cuda_version)
    let runtime = v"12.1",
        compiler = Base.thisminor(CUDA_Compiler_jll.cuda_version)
        if compiler.major != runtime.major
            @error """CUDA_Runtime_jll provides CUDA $runtime, but CUDA_Compiler_jll provides CUDA $compiler.
                       These versions need to have the same major version; call `CUDA.set_runtime_version!` to
                       reconfigure both, or remove stale entries from your LocalPreferences.toml."""
        elseif compiler < runtime
            @warn """CUDA_Runtime_jll provides CUDA $runtime, which is newer than CUDA_Compiler_jll's CUDA $compiler.
                      This is an unsupported combination; call `CUDA.set_runtime_version!` to reconfigure both."""
        end
    end
end
end  # __init__()
