# Autogenerated wrapper script for CUDA_Runtime_jll for x86_64-w64-mingw32-cuda+11.7
export libcublas, libcublasLt, libcudart, libcufft, libcupti, libcurand, libcusolver, libcusolverMg, libcusparse, libnvperf_host, libnvperf_target

using CUDA_Driver_jll
using CUDA_Compiler_jll
JLLWrappers.@generate_wrapper_header("CUDA_Runtime")
JLLWrappers.@declare_library_product(libcublas, "cublas64_11.dll")
JLLWrappers.@declare_library_product(libcublasLt, "cublasLt64_11.dll")
JLLWrappers.@declare_library_product(libcudart, "cudart64_110.dll")
JLLWrappers.@declare_library_product(libcufft, "cufft64_10.dll")
JLLWrappers.@declare_library_product(libcupti, "cupti64_2022.2.1.dll")
JLLWrappers.@declare_library_product(libcurand, "curand64_10.dll")
JLLWrappers.@declare_library_product(libcusolver, "cusolver64_11.dll")
JLLWrappers.@declare_library_product(libcusolverMg, "cusolverMg64_11.dll")
JLLWrappers.@declare_library_product(libcusparse, "cusparse64_11.dll")
JLLWrappers.@declare_library_product(libnvperf_host, "nvperf_host.dll")
JLLWrappers.@declare_library_product(libnvperf_target, "nvperf_target.dll")
function __init__()
    JLLWrappers.@generate_init_header(CUDA_Driver_jll, CUDA_Compiler_jll)
    JLLWrappers.@init_library_product(
        libcublas,
        "bin\\cublas64_11.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcublasLt,
        "bin\\cublasLt64_11.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcudart,
        "bin\\cudart64_110.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcufft,
        "bin\\cufft64_10.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcupti,
        "bin\\cupti64_2022.2.1.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcurand,
        "bin\\curand64_10.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcusolver,
        "bin\\cusolver64_11.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcusolverMg,
        "bin\\cusolverMg64_11.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcusparse,
        "bin\\cusparse64_11.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvperf_host,
        "bin\\nvperf_host.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnvperf_target,
        "bin\\nvperf_target.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
    if isdefined(CUDA_Compiler_jll, :cuda_version)
    let runtime = v"11.7",
        compiler = Base.thisminor(CUDA_Compiler_jll.cuda_version)
        if compiler.major != runtime.major
            @error """CUDA_Runtime_jll provides CUDA $runtime, but CUDA_Compiler_jll provides CUDA $compiler.
                       These versions need to have the same major version; call `CUDA.set_runtime_version!` to
                       reconfigure both, or remove stale entries from your LocalPreferences.toml."""
        elseif compiler < runtime
            @warn """CUDA_Runtime_jll provides CUDA $runtime, which is newer than CUDA_Compiler_jll's CUDA $compiler.
                      This is an unsupported combination; call `CUDA.set_runtime_version!` to reconfigure both."""
        end
    end
end
end  # __init__()
